### ISSUE TITLE
Update Package Version

### ISSUE THREAD

**Issue by JCSmillie** [aysiu/offset#3]
Could you please update the package version of Offset to include your latest code changes? Working on my 10.14 deployment and noticed that your latest changes to support 10.14 better do not appear to be part of the package.  Installing the updated offset file works well in my environment in testing.  Would love to push out.  

Thanks.

**Comment by aysiu** [comment]
Sorry about that, @JCSmillie 

https://github.com/aysiu/offset/releases/tag/1.4.2
